Repository salayo-team/local-life-backend, pull requests merged in 2025-07, with the labels that each got.

#4 📝docs : 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/uiux-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/기능-이슈-템플릿.md
Labels: documentation

#5 :sparkles: feat: Swagger API 문서화 환경 구축
  build.gradle
  src/main/java/com/salayo/locallifebackend/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: feature

#9 ✨ feat : program, category entity 생성, status enum 생성
  README.md
  src/main/java/com/salayo/locallifebackend/domain/category/entity/AptitudeCategory.java
  src/main/java/com/salayo/locallifebackend/domain/category/entity/RegionCategory.java
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateRequest.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/enums/ProgramStatus.java
  src/main/java/com/salayo/locallifebackend/domain/program/repository/ProgramRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
  src/main/java/com/salayo/locallifebackend/global/enums/DeletedStatus.java
Labels: feature

#27 :sparkles: feat : Member 엔티티 및 기본 구조 세팅
  src/main/java/com/salayo/locallifebackend/domain/user/controller/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/user/controller/MemberController.java
  src/main/java/com/salayo/locallifebackend/domain/user/entity/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/user/entity/Member.java
  src/main/java/com/salayo/locallifebackend/domain/user/enums/Gender.java
  src/main/java/com/salayo/locallifebackend/domain/user/enums/MemberRole.java
  src/main/java/com/salayo/locallifebackend/domain/user/repository/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/user/repository/MemberRepository.java
  src/main/java/com/salayo/locallifebackend/domain/user/service/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/user/service/MemberService.java
Labels: feature

#28 :sparkles: feat : JWT 기반 인증/인가 구조 설정
  build.gradle
  src/main/java/com/salayo/locallifebackend/domain/user/repository/MemberRepository.java
  src/main/java/com/salayo/locallifebackend/global/config/RedisConfig.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/security/MemberDetails.java
  src/main/java/com/salayo/locallifebackend/global/security/config/SecurityConfig.java
  src/main/java/com/salayo/locallifebackend/global/security/filter/JwtAuthFilter.java
  src/main/java/com/salayo/locallifebackend/global/security/jwt/JwtProvider.java
  src/main/java/com/salayo/locallifebackend/global/util/RedisUtil.java
  src/main/resources/application.properties
Labels: feature

#31 :building_construction: chore : GitHub Actions CI 설정 추가
  .github/workflows/ci.yml
Labels: chore

#35 :sparkles: feat : S3 파일 업로드 기능 구현
  build.gradle
  src/main/java/com/salayo/locallifebackend/LocalLifeBackendApplication.java
  src/main/java/com/salayo/locallifebackend/domain/file/config/S3Config.java
  src/main/java/com/salayo/locallifebackend/domain/file/controller/FileController.java
  src/main/java/com/salayo/locallifebackend/domain/file/dto/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/file/entity/File.java
  src/main/java/com/salayo/locallifebackend/domain/file/entity/FileMapping.java
  src/main/java/com/salayo/locallifebackend/domain/file/enums/FileCategory.java
  src/main/java/com/salayo/locallifebackend/domain/file/service/FileService.java
  src/main/java/com/salayo/locallifebackend/domain/file/util/S3Uploader.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/success/SuccessCode.java
  src/main/resources/application.properties
Labels: feature, chore, remove

#36 :sparkles: feat: 회원가입 시 이메일 인증 코드 전송 기능 구현
  http/email.http
  src/main/java/com/salayo/locallifebackend/domain/email/config/EmailConfig.java
  src/main/java/com/salayo/locallifebackend/domain/email/controller/EmailController.java
  src/main/java/com/salayo/locallifebackend/domain/email/dto/EmailSendRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/email/service/EmailService.java
  src/main/java/com/salayo/locallifebackend/global/config/RedisConfig.java
  src/main/java/com/salayo/locallifebackend/global/security/config/SecurityConfig.java
  src/main/java/com/salayo/locallifebackend/global/success/SuccessCode.java
  src/main/resources/application.properties
Labels: add, feature, chore

#37 :sparkles: feat: 유효성 검사용 ValidationPatterns 유틸 클래스 추가 및 적용
  src/main/java/com/salayo/locallifebackend/domain/email/dto/EmailSendRequestDto.java
  src/main/java/com/salayo/locallifebackend/global/util/ValidationPatterns.java
Labels: feature

#39 :sparkles: feat : 회원가입 시 이메일 인증 코드 확인 기능 구현
  http/email.http
  src/main/java/com/salayo/locallifebackend/domain/email/controller/EmailController.java
  src/main/java/com/salayo/locallifebackend/domain/email/dto/EmailVerifyRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/email/service/EmailService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/success/SuccessCode.java
  src/main/java/com/salayo/locallifebackend/global/util/ValidationPatterns.java
Labels: feature

#41 ✨  feat : 체험 프로그램 생성 API 관련 구조 수정 및 구현
  build.gradle
  http/Program.http
  http/testImage.png
  src/main/java/com/salayo/locallifebackend/domain/category/entity/AptitudeCategory.java
  src/main/java/com/salayo/locallifebackend/domain/category/repository/AptitudeCategoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/category/repository/RegionCategoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateRequest.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramScheduleTimeRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramScheduleTimeResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/ProgramDay.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/ProgramScheduleTime.java
  src/main/java/com/salayo/locallifebackend/domain/program/enums/DayName.java
  src/main/java/com/salayo/locallifebackend/domain/program/enums/LocalSpecialized.java
  src/main/java/com/salayo/locallifebackend/domain/program/enums/ProgramStatus.java
  src/main/java/com/salayo/locallifebackend/domain/program/repository/ProgramRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
Labels: add, refactor, feature, remove

#44 :bug: fix : RedisTemplate 빈 충돌 해결 및 @Qualifier 명시로 주입 대상 명확화
  src/main/java/com/salayo/locallifebackend/domain/email/service/EmailService.java
  src/main/java/com/salayo/locallifebackend/global/config/RedisConfig.java
  src/main/java/com/salayo/locallifebackend/global/security/jwt/JwtProvider.java
Labels: fix

#49 ✨ feat : Payment, PaymentHistory 도메인 초기 구현
  src/main/java/com/salayo/locallifebackend/domain/member/entity/Member.java
  src/main/java/com/salayo/locallifebackend/domain/payment/controller/PaymentController.java
  src/main/java/com/salayo/locallifebackend/domain/payment/dto/PaymentCreateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/payment/entity/Payment.java
  src/main/java/com/salayo/locallifebackend/domain/payment/enums/PaymentStatus.java
  src/main/java/com/salayo/locallifebackend/domain/payment/repository/PaymentRepository.java
  src/main/java/com/salayo/locallifebackend/domain/payment/service/PaymentService.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/controller/PaymentHistoryController.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/dto/PaymentHistoryResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/entity/PaymentHistory.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/enums/PaymentHistoryStatus.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/repository/PaymentHistoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/service/PaymentService.java
Labels: feature

#51 🚚  rename : PaymentHistory Service 이름 변경
  src/main/java/com/salayo/locallifebackend/domain/member/entity/Member.java
  src/main/java/com/salayo/locallifebackend/domain/paymenthistory/service/PaymentHistoryService.java
Labels: fix, remove

#52 :sparkles: feat : 일반 회원가입 기능 구현(닉네임 자동 생성 및 중복 검사 포함)
  http/auth.http
  http/email.http
  src/main/java/com/salayo/locallifebackend/domain/member/controller/AuthController.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/.gitkeep
  src/main/java/com/salayo/locallifebackend/domain/member/dto/UserSignupRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/UserSignupResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/entity/Member.java
  src/main/java/com/salayo/locallifebackend/domain/member/repository/MemberRepository.java
  src/main/java/com/salayo/locallifebackend/domain/member/service/AuthService.java
  src/main/java/com/salayo/locallifebackend/domain/member/util/NicknameGenerator.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/security/config/SecurityConfig.java
  src/main/java/com/salayo/locallifebackend/global/success/SuccessCode.java
Labels: feature

#53 ♻️ refactor : UIUX issue templates 수정
  .github/ISSUE_TEMPLATE/uiux-이슈-템플릿.md
Labels: documentation, uiux

#56 ✨ feat : Spring AI 기반 백엔드 환경 초기 구축 및 AI 적성 테스트 구조 추가
  build.gradle
  src/main/java/com/salayo/locallifebackend/domain/ai/controller/AiTestController.java
  src/main/java/com/salayo/locallifebackend/domain/ai/prompt/PromptManager.java
  src/main/java/com/salayo/locallifebackend/domain/ai/prompt/PromptType.java
  src/main/java/com/salayo/locallifebackend/domain/ai/service/AiTestService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/service/BaseAiService.java
  src/main/java/com/salayo/locallifebackend/global/config/AiConfig.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/application.properties
  src/main/resources/http/ai-test.http
  src/main/resources/prompts/aptitude-test.txt
Labels: fix, feature, chore, test, backend

#57 ♻️ refactor : 기능 issue templates 수정
  .github/ISSUE_TEMPLATE/기능-이슈-템플릿.md
Labels: documentation, backend

#59 :sparkles: feat : 로그인 기능 구현 및 로컬 크리에이터 승인 상태 체크 추가
  http/Auth.http
  src/main/java/com/salayo/locallifebackend/domain/localcreator/entity/LocalCreator.java
  src/main/java/com/salayo/locallifebackend/domain/localcreator/repository/LocalCreatorRepository.java
  src/main/java/com/salayo/locallifebackend/domain/member/controller/AuthController.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/LoginRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/LoginResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/service/AuthService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/success/SuccessCode.java
Labels: feature

#80 :recycle: 프로젝트 환경 및 코드/문서 스타일 리팩토링
  build.gradle
  src/main/java/com/salayo/locallifebackend/domain/email/controller/EmailController.java
  src/main/java/com/salayo/locallifebackend/domain/email/dto/EmailSendRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/controller/AuthController.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/LoginRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/UserSignupRequestDto.java
Labels: documentation, refactor, chore

#79 ✨ feat : 체험 프로그램 생성 API 구현 및 도메인 구조 변경
  http/Program.http
  src/main/java/com/salayo/locallifebackend/domain/category/entity/AptitudeCategory.java
  src/main/java/com/salayo/locallifebackend/domain/category/entity/RegionCategory.java
  src/main/java/com/salayo/locallifebackend/domain/category/repository/AptitudeCategoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/category/repository/RegionCategoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/localcreator/repository/LocalCreatorRepository.java
  src/main/java/com/salayo/locallifebackend/domain/member/repository/MemberRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramDayResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramScheduleTimeRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramScheduleTimeResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/ProgramDay.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/ProgramScheduleTime.java
  src/main/java/com/salayo/locallifebackend/domain/program/repository/ProgramDayRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/repository/ProgramScheduleTimeRepository.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
Labels: add, refactor, feature, remove

#88 🔧 add : 체험 프로그램 생성 API 파일 업로드 로직 추가
  src/main/java/com/salayo/locallifebackend/domain/file/enums/FilePurpose.java
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/dto/ProgramCreateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/auth.http
  src/main/resources/http/bank_account.png
  src/main/resources/http/buisness_reg.png
  src/main/resources/http/email.http
  src/main/resources/http/program.http
  src/main/resources/http/testImage.png
Labels: add

#89 :sparkles: feat : CommandLineRunner 및 환경변수 기반 관리자 계정 자동 생성 기능 추가
  src/main/java/com/salayo/locallifebackend/domain/admin/service/AdminAccountService.java
  src/main/java/com/salayo/locallifebackend/domain/admin/util/AdminAccountCommandLineRunner.java
  src/main/java/com/salayo/locallifebackend/domain/member/enums/Gender.java
  src/main/resources/application.properties
Labels: feature, chore

#93 ✨  feat : 체험 프로그램 스케줄 생성 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
  src/main/java/com/salayo/locallifebackend/domain/programschedule/entity/ProgramSchedule.java
Labels: add, feature

#96 :sparkles: feat : 비밀번호 재설정 인증 및 변경 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/member/controller/AuthController.java
  src/main/java/com/salayo/locallifebackend/domain/member/dto/PasswordResetVerifyRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/member/entity/Member.java
  src/main/java/com/salayo/locallifebackend/domain/member/service/AuthService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/auth.http
Labels: feature

#119 ✨ feat : ProgramGroup Entity & Repository 생성, Program Entity 단방향 연관관계 추가
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/ProgramGroup.java
  src/main/java/com/salayo/locallifebackend/domain/program/repository/ProgramGroupRepository.java
Labels: feature

#139 :sparkles: feat : 매거진 파일 업로드 구현
  src/main/java/com/salayo/locallifebackend/domain/magazine/controller/AdminMagazineController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/dto/MagazineFileUploadResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineFileService.java
  src/main/resources/http/magazine.http
Labels: feature

#140 :wrench: 회원가입 이메일 인증 체크 추가 및 지역명 2글자 통일
  src/main/java/com/salayo/locallifebackend/domain/member/service/AuthService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/init/CategoryDataInit.java
Labels: add

#141 :sparkles: feat : 관리자 임시등록(DRAFT) 매거진 목록 조회 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/magazine/controller/AdminMagazineController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/dto/MagazineDraftListResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/entity/Magazine.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineService.java
  src/main/resources/http/magazine.http
Labels: feature

#143 ✨ feat : 리뷰 기능 전체 CRUD 및 정책 로직 구현
  src/main/java/com/salayo/locallifebackend/domain/review/controller/ReviewController.java
  src/main/java/com/salayo/locallifebackend/domain/review/controller/ReviewReplyController.java
  src/main/java/com/salayo/locallifebackend/domain/review/dto/ReviewReplyRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/review/dto/ReviewReplyResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/review/entity/Review.java
  src/main/java/com/salayo/locallifebackend/domain/review/entity/ReviewReply.java
  src/main/java/com/salayo/locallifebackend/domain/review/repository/ReviewReplyRepository.java
  src/main/java/com/salayo/locallifebackend/domain/review/repository/ReviewRepository.java
  src/main/java/com/salayo/locallifebackend/domain/review/service/ReviewCacheService.java
  src/main/java/com/salayo/locallifebackend/domain/review/service/ReviewReplyService.java
  src/main/java/com/salayo/locallifebackend/domain/review/service/ReviewService.java
  src/main/java/com/salayo/locallifebackend/global/config/RedisConfig.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/util/CacheKeyPrefix.java
  src/main/resources/http/review.http
Labels: fix, refactor, feature, test, backend

#147 :sparkles: feat : 임시등록(DRAFT) 매거진 상세조회 및 파일 자동매핑 기능 추가
  src/main/java/com/salayo/locallifebackend/domain/file/repository/FileMappingRepository.java
  src/main/java/com/salayo/locallifebackend/domain/localcreator/repository/LocalCreatorRepository.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/controller/AdminMagazineController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/dto/MagazineDraftDetailResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineFileService.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineService.java
  src/main/java/com/salayo/locallifebackend/global/config/SwaggerConfig.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/magazine.http
Labels: feature, chore

#149 ✨  feat : 체험 프로그램 삭제 API 구현, 체험 프로그램 등록 API 수정, ProgramStatus Enum 추가
  src/main/java/com/salayo/locallifebackend/domain/program/controller/ProgramController.java
  src/main/java/com/salayo/locallifebackend/domain/program/entity/Program.java
  src/main/java/com/salayo/locallifebackend/domain/program/enums/ProgramStatus.java
  src/main/java/com/salayo/locallifebackend/domain/program/service/ProgramService.java
  src/main/java/com/salayo/locallifebackend/domain/programschedule/entity/ProgramSchedule.java
  src/main/java/com/salayo/locallifebackend/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/program.http
Labels: feature

#150 ♻️ refactor : 온보딩 적성 AI 추천 기능 구조 개선 및 Swagger 문서화
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/controller/AptitudeController.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeAnswerRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeQuestionResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeTestResultResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeTestStartResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeTextProgressResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/CanRetakeTestResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/enums/AptitudeType.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeCacheService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/util/CacheKeyPrefix.java
Labels: documentation, add, refactor, backend
