Repository salayo-team/local-life-backend, pull requests merged in 2025-09, with the labels that each got.

#157 ✨ feat : AI 공통 JSON 응답 파싱 추가 및 ChatClient 빈 주입 오류 수정
  src/main/java/com/salayo/locallifebackend/domain/ai/service/BaseAiService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
Labels: fix, feature, backend

#159 :sparkles: feat : 매거진 피드백(수정 요청) 등록 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/controller/MagazineFeedbackController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/dto/MagazineFeedbackCreateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/dto/MagazineFeedbackResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/entity/MagazineFeedback.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/repository/MagazineFeedbackRepository.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/service/MagazineFeedbackService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/magazine.http
Labels: feature

#165 :sparkles: feat : 관리자 매거진 수정 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/email/service/EmailService.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/controller/AdminMagazineController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/dto/MagazineUpdateRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/entity/Magazine.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/entity/MagazineRevision.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/enums/MagazineStatus.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/repository/MagazineRevisionRepository.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/magazine.http
Labels: feature

#166 ✨ feat : AI 적성 검사 세션 기반 이력 저장 및 조회 기능 구현
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/controller/AptitudeController.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeTestHistoryResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/entity/AptitudeTestHistory.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/repository/AptitudeTestHistoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeCacheService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/util/CacheKeyPrefix.java
  src/main/resources/http/ai-aptitude.http
Labels: fix, refactor, feature, performance, remove, test, backend

#171 ✨ feat : 적성 검사 이어하기 및 AI 대화형 적성 검사 재설계
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/controller/AptitudeController.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AiAnswerValidationDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AiQuestionGenerationDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeAnswerRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeResumeResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/dto/AptitudeSelectRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/entity/AptitudeTestHistory.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/entity/UserAptitude.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/repository/AptitudeTestHistoryRepository.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeAiService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeCacheService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeService.java
  src/main/java/com/salayo/locallifebackend/domain/ai/aptitude/service/AptitudeTestHistoryService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/java/com/salayo/locallifebackend/global/util/CacheKeyPrefix.java
  src/main/resources/application.properties
  src/main/resources/http/ai-aptitude.http
Labels: fix, add, refactor, feature, performance, chore, remove, test

#173 :sparkles: feat: 매거진 피드백 제약 로직 추가 및 조회 로직 수정
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/controller/MagazineFeedbackController.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/dto/MagazineFeedbackResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/entity/MagazineFeedback.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/repository/MagazineFeedbackRepository.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/feedback/service/MagazineFeedbackService.java
  src/main/java/com/salayo/locallifebackend/domain/magazine/service/MagazineService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/magazine.http
Labels: add, refactor, feature

#174 ✨ feat : 온보딩 단계 관리 및 분기 로직/상태 관리 구현
  src/main/java/com/salayo/locallifebackend/domain/onboarding/controller/OnboardingController.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/dto/OnboardingAptitudeCheckRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/dto/OnboardingProgressResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/dto/OnboardingRegionRequestDto.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/dto/OnboardingStatusResponseDto.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/entity/OnboardingProgress.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/enums/OnboardingStep.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/enums/RegionType.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/repository/OnboardingProgressRepository.java
  src/main/java/com/salayo/locallifebackend/domain/onboarding/service/OnboardingService.java
  src/main/java/com/salayo/locallifebackend/global/error/ErrorCode.java
  src/main/resources/http/onboarding.http
Labels: add, refactor, branch, feature, remove, test, low priority
